# Generated by Django 3.0.8 on 2020-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200729_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='body',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
