# Generated by Django 3.0.8 on 2020-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200731_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='body',
            field=models.TextField(max_length=1000, verbose_name='Ваш ответ'),
        ),
    ]
